# Generated by Django 4.2.4 on 2024-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humantext', '0002_customusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpurchase',
            name='Expiry_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
