# Generated by Django 4.2.4 on 2024-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humantext', '0003_planpurchase_expiry_status_delete_customusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Word_Limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Benfit',
            field=models.TextField(),
        ),
    ]
